### PR TITLE
migrate to latest version of casbin

### PR DESCRIPTION
**Pull request by hmdsefi**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@hmdsefi it's Casbin, instead of Casdoor

**Comment by hsluoyz** [comment]
@memwey

**Comment by hsluoyz** [comment]
@hmdsefi why close?

**Comment by hmdsefi** [comment]
> @hmdsefi why close?

@hsluoyz It seams @memwey is not active. Do you think I should reopen it or wait for him to reopen it?

**Comment by hmdsefi** [comment]
reopen

**Comment by hsluoyz** [comment]
@hmdsefi you can wait for a few days, if still no activities on this repo, you can create PR to: https://github.com/casbin/sqlx-adapter

**Pull request closed without merging**
